"""empty message

Revision ID: 3a8f1b7673dc
Revises: None
Create Date: 2017-12-17 03:31:42.767281

"""

# revision identifiers, used by Alembic.
revision = '3a8f1b7673dc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    ### end Alembic commands ###
